[package]
name = "pristine-rust-lib"
version = "0.1.0"
authors = ["Mike Lubinets <me@mkl.dev>"]
edition = "2018"
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
